### Spring properties
# Service registers under this name
spring:
  application:
    name: sorookin-ms

# Discovery Server Access
eureka:
  instance:
    metadataMap:
      type: extractor
      friendlyname: Sorookin
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server (Tomcat) Port
server: 
  port: 2227

# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled: false